logger:
  file:
    path: /var/log/open5gs/smf.log
    level: trace

db_uri: mongodb://10.103.238.239/open5gs

smf:
  sbi:
    server:
      - address: 10.100.200.67
        port: 7777
    client:
      nrf:
        - uri: http://10.100.200.10:7777

  gtpc:
    server:
      - address: 10.100.200.67

  gtpu:                           
    server:
      - address: 10.100.200.67

  pfcp:
    server:
      - address: 10.100.200.67
    client:
      upf:
        - address: 10.100.200.117
          dnn: enterprise

  metrics:
    server:
      - address: 0.0.0.0
        port: 9090

  session:
    - subnet: 10.45.18.0/16
      gateway: 10.45.18.1
      dnn: enterprise
      s_nssai:
        - sst: 1
          sd: "000004"

  dns:
    - 8.8.8.8
    - 8.8.4.4
