logger:
  file:
    path: /var/log/open5gs/smf.log
    level: trace

db_uri: mongodb://10.103.238.239/open5gs

smf:
  sbi:
    server:
      - address: 10.100.200.61
        port: 7777
    client:
      nrf:
        - uri: http://10.100.200.10:7777

  gtpc:
    server:
      - address: 10.100.200.61

  gtpu:                           
    server:
      - address: 10.100.200.61

  pfcp:
    server:
      - address: 10.100.200.61
    client:
      upf:
        - address: 10.100.200.111
          dnn: miot

  metrics:
    server:
      - address: 0.0.0.0
        port: 9090

  session:
    - subnet: 10.45.12.0/16
      gateway: 10.45.12.1
      dnn: miot
      s_nssai:
        - sst: 3
          sd: "000003"

  dns:
    - 8.8.8.8
    - 8.8.4.4
