logger:
  file:
    path: /var/log/open5gs/upf.log
    level: trace

upf:
  pfcp:
    server:
      - address: 10.100.200.127
    client:
      smf:
        - address: 10.100.200.50

  gtpu:
    server:
      - address: 10.100.200.127

  metrics:
    server:
      - address: 0.0.0.0
        port: 9090

  session:
    - subnet: 10.45.28.0/24
      gateway: 10.45.28.1
      dnn: internet
