logger:
  file:
    path: /var/log/open5gs/nef.log
    level: trace
nef:
  sbi:
    server:
      - address: 10.100.200.12
        port: 7777
    client:
      nrf:
        - uri: http://10.100.200.10:7777
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
