logger:

  file:

    path: /var/log/open5gs/upf.log
    level: trace

upf:

  pfcp:

    server:

      - address: 10.100.200.43

    client:

      smf:

        - address: 10.100.200.53

  gtpu:

    server:

      - address: 10.100.200.43

  metrics:

    server:

      - address: 0.0.0.0

        port: 9090
      
  session:

    - subnet: 10.49.0.0/16

      gateway: 10.49.0.1

      dnn: urllc